"""create_initial_tables

Revision ID: 794c034791f2
Revises: 
Create Date: 2026-08-18 00:36:28.013110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794c034791f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    op.create_table('linked_accounts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_accounts_user_id'), 'linked_accounts', ['user_id'], unique=False)
    
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('date_is_inferred', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['linked_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- Enable & FORCE Row-Level Security (RLS) ---
    op.execute("ALTER TABLE linked_accounts ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE linked_accounts FORCE ROW LEVEL SECURITY;")

    op.execute("ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE tasks FORCE ROW LEVEL SECURITY;")

    # --- Create Isolation Policies ---
    op.execute("""
        CREATE POLICY user_isolation_linked_accounts ON linked_accounts
        FOR ALL
        USING (user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid);
    """)

    op.execute("""
        CREATE POLICY user_isolation_tasks ON tasks
        FOR ALL
        USING (user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid);
    """)

    # --- Add Check Constraints ---
    op.create_check_constraint("check_user_email_format", "users", "email LIKE '%@%.%'")
    op.create_check_constraint("check_task_status", "tasks", "status IN ('pending', 'completed', 'dismissed')")


def downgrade() -> None:
    """Downgrade schema."""
    # --- Drop Check Constraints Safely ---
    op.execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS check_task_status;")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS check_user_email_format;")

    # --- Drop RLS Policies & Disable FORCE RLS ---
    op.execute("DROP POLICY IF EXISTS user_isolation_tasks ON tasks;")
    op.execute("DROP POLICY IF EXISTS user_isolation_linked_accounts ON linked_accounts;")
    op.execute("ALTER TABLE tasks NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE linked_accounts NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE linked_accounts DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_linked_accounts_user_id'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
